# Generated by Django 4.1.3 on 2023-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfielFeedItem',
            new_name='ProfileFeedItem',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
